config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :arvs
  resources :dosages
  resources :moh_names
  resources :regimens
  resources :regimen_combinations, path: 'combinations'

  namespace :metadata do
    get 'openmrs', to: 'openmrs'
    get 'moh', to: 'moh'
  end

  root to: 'regimens#index'
end

app/models/alternative_drug_name.rb
class AlternativeDrugName < ApplicationRecord
  belongs_to :drug, foreign_key: :drug_inventory_id
  
  validates_presence_of :name, :drug_inventory_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
# frozen_string_literal: true

class Concept < ApplicationRecord
  self.table_name = :concept
  self.primary_key = :concept_id

  has_many :concept_names
  has_many :concept_set 
  has_many :drugs
  has_many :concept_members, class_name: 'ConceptSet', foreign_key: :concept_set

  def self.find_all_by_name(concept_name)
    Concept.joins(:concept_names)
           .merge(ConceptName.where(name: concept_name, voided: false))
           .where(retired: false)
  end
end

app/models/concept_name.rb
# frozen_string_literal: true

class ConceptName < ApplicationRecord
  self.table_name = :concept_name
  self.primary_key = :concept_name_id

  belongs_to :concept
end

app/models/concept_set.rb
# frozen_string_literal: true

class ConceptSet < ApplicationRecord
  self.table_name = :concept_set
  self.primary_key = :concept_set_id

  belongs_to :set, foreign_key: :concept_set, class_name: 'Concept'
  belongs_to :concept
end

app/models/drug.rb
class Drug < ApplicationRecord
  self.table_name = :drug
  self.primary_key = :drug_id

  belongs_to :concept
  has_many :alternative_names, class_name: 'AlternativeDrugName', foreign_key: 'drug_inventory_id'

  scope(:all_arvs, lambda do
    arvs_concept = Concept.find_all_by_name('Antiretroviral Drugs')
    arv_drugs_concepts = ConceptSet.where(set: arvs_concept)

    where(concept: arv_drugs_concepts, retired: false).includes(:alternative_names)
  end)

  def moh_name
    @moh_name ||= (alternative_names.first&.name || name)
  end
end

app/models/moh_regimen.rb
class MohRegimen < ApplicationRecord
  self.table_name =  'moh_regimens'
  self.primary_key = 'regimen_id'

  has_many :ingredients, class_name: 'MohRegimenIngredients'
  has_many :starter_pack_ingredients, class_name: 'MohRegimenIngredientStarterPacks'
end

app/models/moh_regimen_dose.rb
class MohRegimenDose < ApplicationRecord
  self.table_name = 'moh_regimen_doses'
  self.primary_key = 'dose_id'

  has_many :ingredients, class_name: 'MohRegimenIngredients',
                         foreign_key: :dose_id
end

app/models/moh_regimen_lookup.rb
# frozen_string_literal: true

class MohRegimenLookup < ApplicationRecord
  self.table_name = 'moh_regimen_lookup'
  self.primary_key = 'regimen_lookup_id'
end

app/models/regimen.rb
class Regimen < ApplicationRecord
  self.table_name = :moh_regimen_name
  self.primary_key = :regimen_name_id

  has_many :combinations, class_name: 'RegimenCombination',
                          foreign_key: :regimen_name_id
  has_many :ingredients, class_name: 'RegimenIngredient',
                         foreign_key: 'ingredient_id'

  accepts_nested_attributes_for :combinations, allow_destroy: true
end

app/models/regimen_combination.rb
class RegimenCombination < ApplicationRecord
  self.table_name = :moh_regimen_combination
  self.primary_key = :regimen_combination_id

  belongs_to :regimen, foreign_key: :regimen_name_id

  has_many :drugs, class_name: 'RegimenCombinationDrug'

  accepts_nested_attributes_for :drugs, allow_destroy: true

  def name
    drugs.sort_by(&:name).collect(&:name).join(' + ')
  end
end

app/models/regimen_dose.rb
class RegimenDose < ApplicationRecord
  self.table_name = 'moh_regimen_doses'
  self.primary_key = 'dose_id'

  has_many :ingredients, class_name: 'RegimenIngredient',
                         foreign_key: :dose_id
end

app/models/regimen_index.rb
class RegimenIndex < ApplicationRecord
  self.table_name =  'moh_regimens'
  self.primary_key = 'regimen_id'

  has_many :ingredients, class_name: 'MohRegimenIngredients'
  has_many :starter_pack_ingredients, class_name: 'MohRegimenIngredientStarterPacks'
end

app/models/regimen_ingredient.rb
class RegimenIngredient < ApplicationRecord
  self.table_name = 'moh_regimen_ingredient'
  self.primary_key = 'ingredient_id'

  belongs_to :drug, foreign_key: :drug_inventory_id
  belongs_to :dose, class_name: 'RegimenDose', foreign_key: :dose_id
  belongs_to :regimen, class_name: 'Regimen', foreign_key: :regimen_id
end

app/models/regimen_lookup.rb
# frozen_string_literal: true

class RegimenLookup < ApplicationRecord
  self.table_name = 'moh_regimen_lookup'
  self.primary_key = 'regimen_lookup_id'
end

app/controllers/arvs_controller.rb
# frozen_string_literal: true

class ArvsController < ApplicationController
  def index
    @arvs = DrugService.all_arvs
  end

  def show
    @arv = Drug.find(params[:id])
    @ingredients = RegimenIngredient.includes(:dose).where(drug: @arv)
    @regimens = Regimen.joins(:ingredients).merge(RegimenIngredient.where(drug: @arv))
  end

  def edit
    @arv = Drug.find(params[:id])
    @ingredients = RegimenIngredient.includes(:dose).where(drug: @arv)
    @regimens = Regimen.joins(:ingredients).merge(RegimenIngredient.where(drug: @arv))
  end
end

app/controllers/dosages_controller.rb
class DosagesController < ApplicationController
  def index
    @drug_dosages = drug_dosages
  end

  def edit
    @drug = Drug.find(params[:id])
    @dosages = RegimenIngredient.where(drug: @drug).sort_by do |ingredient|
      [ingredient.regimen.name, ingredient.min_weight]
    end
    @doses = RegimenDose.all
  end

  private

  def drug_dosages
    asll_ingredients.each_with_object({}) do |dosage, dosages|
      dosages[dosage.drug] = [] unless dosages.include?(dosage.drug)

      next if dosages[dosage.drug].find { |d| d.min_weight == dosage.min_weight }

      dosages[dosage.drug] << dosage
    end
  end

  def all_ingredients
    RegimenIngredient.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, model_form, association, **kwargs)
    new_object = model_form.object.send(association).klass.new
    id = new_object.object_id
    fields = model_form.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", form: builder)
    end

    if kwargs.include?(:class)
      kwargs[:class] += ' add_fields'
    else
      kwargs[:class] = 'add_fields'
    end
    
    link_to(name, '#', data: {id: id, fields: fields.gsub("\n", "")}, **kwargs)
  end
end

app/helpers/dosages_helper.rb
module DosagesHelper
  MOH_WEIGHT_BANDS = [[3, 5.9],
                      [6, 9.9],
                      [10, 13.9],
                      [14, 19.9],
                      [20, 24.9],
                      [25, 29.9],
                      [30, 34.9],
                      [35, 39.9],
                      [40, 49.9],
                      [50, nil]].freeze

  def breakdown_to_moh_dosages(dosages)
    MOH_WEIGHT_BANDS.map do |weight_band|
      min_value, max_value = weight_band

      matching_dosage = dosages.find do |dosage|
        min_value >= dosage.min_weight\
          && (max_value && max_value <= dosage.max_weight)\
          || (max_value.nil? && min_value < dosage.max_weight)
      end

      next nil unless matching_dosage

      OpenStruct.new(am: matching_dosage.dose.am, pm: matching_dosage.dose.pm)
    end
  end
end

app/helpers/moh_names_helper.rb
module MohNamesHelper
end

app/helpers/regimens_helper.rb
module RegimensHelper
  def arvs
    Drug.all_arvs
        .sort_by(&:moh_name)
        .map { |arv| [arv.moh_name, arv.id] }
  end
end

app/views/arvs/_edit_form.html.erb
<% unless regimen.errors.empty? %>
  <div class="alert alert-danger" role="alert">
    <ul>
      <% regimen.errors.each do |item, error| %>
        <li><%= item %> - <%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for regimen, url: { action: :update } do |form| %>
  <%= form.fields_for :combinations, RegimenCombination.new do |combos_form| %>
    <%= render 'combination_fields', form: combos_form %>
  <% end %>

  <%= link_to_add_fields '+ Combination', form, :combinations, class: 'btn btn-outline-primary waves-effect', style: 'margin-top: 5px'%>

  <hr />

  <%= form.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/arvs/edit.html.erb
<div class="container">
  <h1><%= @arv.name %></h1>

  <%= form_with url: { action: :update } do |form| %>
    <%= form.label 'Dose', for: :dose %>
    <%= form.select :dose, RegimenDose.all.map { |dose| ["AM: #{dose.am}, PM: #{dose.pm}", dose.dose_id] }, {}, class: 'form-select form-select-lg' %>
    <hr />

    <%= form.submit 'Save', class: 'btn btn-primary' %>
  <% end %>
</div>

<%= javascript_pack_tag 'regimens/edit' %>

app/views/arvs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12">
      <h1><%= @arv.name %></h1>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-12">
      <h6 class="text-muted">
        <%= @arv.moh_name %>
        <a href="<%= edit_moh_name_path(@arv.alternative_names.first) %>" class="btn btn-link text-primary"><i class="fas fa-edit"></i></a>
      </h6>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-1">
      <span class="fw-bold">Regimens:</span>
    </div>
    <div class="col-sm-8">
      <ul class="list-inline">
        <% @regimens.each do |regimen| %>
          <li class="list-inline-item"><%= regimen.name %></li>
        <% end %>
      </ul>
    </div>
  </div>
  
  <div class="row">
    <div class="col-sm-12">
      <h4>Doses</h4>
    </div>
  </div>


  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
          <th>Min. Weight</th>
          <th>Max. Weight</th>
          <th>AM</th>
          <th>PM</th>
        </thead>
        <tbody>
          <% @ingredients.each do |ingredient| %>
            <tr>
              <td><%= ingredient.min_weight %></td>
              <td><%= ingredient.max_weight %></td>
              <td><%= ingredient.dose.am %></td>
              <td><%= ingredient.dose.pm %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div>