config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :arvs
  resources :dosages
  resources :moh_names
  resources :regimens
  resources :regimen_combinations, path: 'combinations'

  namespace :metadata do
    get 'openmrs', to: 'openmrs'
    get 'moh', to: 'moh'
  end

  root to: 'regimens#index'
end

app/models/alternative_drug_name.rb
class AlternativeDrugName < ApplicationRecord
  belongs_to :drug, foreign_key: :drug_inventory_id
  
  validates_presence_of :name, :drug_inventory_id
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concept.rb
# frozen_string_literal: true

class Concept < ApplicationRecord
  self.table_name = :concept
  self.primary_key = :concept_id

  has_many :concept_names
  has_many :concept_set 
  has_many :drugs
  has_many :concept_members, class_name: 'ConceptSet', foreign_key: :concept_set

  def self.find_all_by_name(concept_name)
    Concept.joins(:concept_names)
           .merge(ConceptName.where(name: concept_name, voided: false))
           .where(retired: false)
  end
end

app/models/concept_name.rb
# frozen_string_literal: true

class ConceptName < ApplicationRecord
  self.table_name = :concept_name
  self.primary_key = :concept_name_id

  belongs_to :concept
end

app/models/concept_set.rb
# frozen_string_literal: true

class ConceptSet < ApplicationRecord
  self.table_name = :concept_set
  self.primary_key = :concept_set_id

  belongs_to :set, foreign_key: :concept_set, class_name: 'Concept'
  belongs_to :concept
end

app/models/drug.rb
class Drug < ApplicationRecord
  self.table_name = :drug
  self.primary_key = :drug_id

  belongs_to :concept
  has_many :alternative_names, class_name: 'AlternativeDrugName', foreign_key: 'drug_inventory_id'

  scope(:all_arvs, lambda do
    arvs_concept = Concept.find_all_by_name('Antiretroviral Drugs')
    arv_drugs_concepts = ConceptSet.where(set: arvs_concept)

    where(concept: arv_drugs_concepts, retired: false).includes(:alternative_names)
  end)

  def moh_name
    @moh_name ||= (alternative_names.first&.name || name)
  end
end

app/models/moh_regimen.rb
class MohRegimen < ApplicationRecord
  self.table_name =  'moh_regimens'
  self.primary_key = 'regimen_id'

  has_many :ingredients, class_name: 'MohRegimenIngredients'
  has_many :starter_pack_ingredients, class_name: 'MohRegimenIngredientStarterPacks'
end

app/models/moh_regimen_dose.rb
class MohRegimenDose < ApplicationRecord
  self.table_name = 'moh_regimen_doses'
  self.primary_key = 'dose_id'

  has_many :ingredients, class_name: 'MohRegimenIngredients',
                         foreign_key: :dose_id
end

app/models/moh_regimen_lookup.rb
# frozen_string_literal: true

class MohRegimenLookup < ApplicationRecord
  self.table_name = 'moh_regimen_lookup'
  self.primary_key = 'regimen_lookup_id'
end

app/models/regimen.rb
class Regimen < ApplicationRecord
  self.table_name = :moh_regimen_name
  self.primary_key = :regimen_name_id

  has_many :combinations, class_name: 'RegimenCombination',
                          foreign_key: :regimen_name_id
  has_many :ingredients, class_name: 'RegimenIngredient',
                         foreign_key: 'ingredient_id'

  accepts_nested_attributes_for :combinations, allow_destroy: true
end

app/models/regimen_combination.rb
class RegimenCombination < ApplicationRecord
  self.table_name = :moh_regimen_combination
  self.primary_key = :regimen_combination_id

  belongs_to :regimen, foreign_key: :regimen_name_id

  has_many :drugs, class_name: 'RegimenCombinationDrug'

  accepts_nested_attributes_for :drugs, allow_destroy: true

  def name
    drugs.sort_by(&:name).collect(&:name).join(' + ')
  end
end

app/models/regimen_dose.rb
class RegimenDose < ApplicationRecord
  self.table_name = 'moh_regimen_doses'
  self.primary_key = 'dose_id'

  has_many :ingredients, class_name: 'RegimenIngredient',
                         foreign_key: :dose_id
end

app/models/regimen_index.rb
class RegimenIndex < ApplicationRecord
  self.table_name =  'moh_regimens'
  self.primary_key = 'regimen_id'

  has_many :ingredients, class_name: 'MohRegimenIngredients'
  has_many :starter_pack_ingredients, class_name: 'MohRegimenIngredientStarterPacks'
end

app/models/regimen_ingredient.rb
class RegimenIngredient < ApplicationRecord
  self.table_name = 'moh_regimen_ingredient'
  self.primary_key = 'ingredient_id'

  belongs_to :drug, foreign_key: :drug_inventory_id
  belongs_to :dose, class_name: 'RegimenDose', foreign_key: :dose_id
  belongs_to :regimen, class_name: 'Regimen', foreign_key: :regimen_id
end

app/models/regimen_lookup.rb
# frozen_string_literal: true

class RegimenLookup < ApplicationRecord
  self.table_name = 'moh_regimen_lookup'
  self.primary_key = 'regimen_lookup_id'
end

app/controllers/arvs_controller.rb
# frozen_string_literal: true

class ArvsController < ApplicationController
  def index
    @arvs = DrugService.all_arvs
  end

  def show
    @arv = Drug.find(params[:id])
    @ingredients = RegimenIngredient.includes(:dose).where(drug: @arv)
    @regimens = Regimen.joins(:ingredients).merge(RegimenIngredient.where(drug: @arv))
  end

  def edit
    @arv = Drug.find(params[:id])
    @ingredients = RegimenIngredient.includes(:dose).where(drug: @arv)
    @regimens = Regimen.joins(:ingredients).merge(RegimenIngredient.where(drug: @arv))
  end
end

app/controllers/dosages_controller.rb
class DosagesController < ApplicationController
  def index
    @drug_dosages = drug_dosages
  end

  def edit
    @drug = Drug.find(params[:id])
    @dosages = RegimenIngredient.where(drug: @drug).sort_by do |ingredient|
      [ingredient.regimen.name, ingredient.min_weight]
    end
    @doses = RegimenDose.all
  end

  private

  def drug_dosages
    asll_ingredients.each_with_object({}) do |dosage, dosages|
      dosages[dosage.drug] = [] unless dosages.include?(dosage.drug)

      next if dosages[dosage.drug].find { |d| d.min_weight == dosage.min_weight }

      dosages[dosage.drug] << dosage
    end
  end

  def all_ingredients
    RegimenIngredient.all
  end
end

app/controllers/metadata_controller.rb
# frozen_string_literal: true

class MetadataController < ApplicationController
  def openmrs
    send_data MetadataService.dump_openmrs_metadata, filename: 'openmrs_metadata_1_7.sql'
  end
  
  def moh
    send_data MetadataService.dump_moh_metadata, filename: 'moh_regimens_v2020.sql'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_add_fields(name, model_form, association, **kwargs)
    new_object = model_form.object.send(association).klass.new
    id = new_object.object_id
    fields = model_form.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", form: builder)
    end

    if kwargs.include?(:class)
      kwargs[:class] += ' add_fields'
    else
      kwargs[:class] = 'add_fields'
    end
    
    link_to(name, '#', data: {id: id, fields: fields.gsub("\n", "")}, **kwargs)
  end
end

app/helpers/dosages_helper.rb
module DosagesHelper
  MOH_WEIGHT_BANDS = [[3, 5.9],
                      [6, 9.9],
                      [10, 13.9],
                      [14, 19.9],
                      [20, 24.9],
                      [25, 29.9],
                      [30, 34.9],
                      [35, 39.9],
                      [40, 49.9],
                      [50, nil]].freeze

  def breakdown_to_moh_dosages(dosages)
    MOH_WEIGHT_BANDS.map do |weight_band|
      min_value, max_value = weight_band

      matching_dosage = dosages.find do |dosage|
        min_value >= dosage.min_weight\
          && (max_value && max_value <= dosage.max_weight)\
          || (max_value.nil? && min_value < dosage.max_weight)
      end

      next nil unless matching_dosage

      OpenStruct.new(am: matching_dosage.dose.am, pm: matching_dosage.dose.pm)
    end
  end
end

app/helpers/moh_names_helper.rb
module MohNamesHelper
end

app/helpers/regimens_helper.rb
module RegimensHelper
  def arvs
    Drug.all_arvs
        .sort_by(&:moh_name)
        .map { |arv| [arv.moh_name, arv.id] }
  end
end

app/views/dosages/_dosages.html.erb
<table class="table table-striped">
  <thead>
    <td>Regimen</td>
    <td>Min. Weight</td>
    <td>Max. Weight</td>
    <td>AM</td>
    <td>PM</td>
    <td>
  </thead>
  <tbody>
    <% dosages.each do |dosage| %>
      <tr>
        <td><%= dosage.regimen.name %></td>
        <td><%= dosage.min_weight %></td>
        <td><%= dosage.max_weight %></td>
        <td><%= dosage.dose.am %></td>
        <td><%= dosage.dose.pm %></td>
        <td>
          <%= link_to 'X', dosage_path(dosage.drug_inventory_id, ingredient_id: dosage.ingredient_id), method: :delete,
                                                                                                       class: 'btn btn-link text-danger',
                                                                                                       data: { confirm: 'Are you sure about deleting this weight?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</ul>

app/views/dosages/edit.html.erb
<div class="container">
  <h1><%= @drug.name %></h1>

  <%= render 'dosages', dosages: @dosages %>
</div>

<%= javascript_pack_tag 'regimens/edit' %>

app/views/dosages/index.html.erb
<div class="container">
  <h1>Dosages</h1>

  <table id="dosages-table" class="table table-striped table-bordered">
    <thead>
      <td class="dosage-drug-name">Drug name</th>
      <td class="dosage-cell">3 - 5.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">6 - 9.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">10 - 13.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">14 - 19.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">20 - 24.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">25 - 29.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">30 - 34.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">35 - 39.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">40 - 49.9kg<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">50kg+<br/><span class="dosage-am">AM</span><span class="dosage-pm">PM</span></td>
      <td class="dosage-cell">Actions</td>
    </thead>
    <tbody>
      <% @drug_dosages.each do |drug, dosages| %>
        <tr>
          <td class="dosage-drug-name"><%= drug.moh_name %></td>
          <% breakdown_to_moh_dosages(dosages).each do |dosage| %>
            <% if dosage %>
              <td class="dosage-cell">
                <div>
                  <span class="dosage-am"><%= dosage.am %></span>
                  <span class="dosage-pm"><%= dosage.pm %></span>
                </div>
              </td>
            <% else %>
              <td></td>
            <% end %>
          <% end %>
          <td class="dosage-cell">
            <a href="<%= edit_dosage_path(drug.id) %>" class="btn btn-link text-primary icon-button"><i class="fas fa-edit mr-1"></i></a>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<style>
  .dosage-cell {
    min-width: 120px;
    font-weight: bold;
  }

  .dosage-drug-name {
    min-width: 240px;
  }

  .dosage-am {
    text-align: left;
    padding-right: 10px;
  }
  
  .dosage-pm {
    text-align: right;
    padding-left: 10px;
  }
</style>

<%= javascript_pack_tag 'dosages/index' %>