config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :arvs
  resources :dosages
  resources :moh_names
  resources :regimens
  resources :regimen_combinations, path: 'combinations'

  namespace :metadata do
    get 'openmrs', to: 'openmrs'
    get 'moh', to: 'moh'
  end

  root to: 'regimens#index'
end

app/models/regimen.rb
class Regimen < ApplicationRecord
  self.table_name = :moh_regimen_name
  self.primary_key = :regimen_name_id

  has_many :combinations, class_name: 'RegimenCombination',
                          foreign_key: :regimen_name_id
  has_many :ingredients, class_name: 'RegimenIngredient',
                         foreign_key: 'ingredient_id'

  accepts_nested_attributes_for :combinations, allow_destroy: true
end

app/controllers/regimens_controller.rb
class RegimensController < ApplicationController
  REGIMEN_SORT_POSITION_LAST = 1_000_000 # Hopefully we will never have this many regimens

  def show
    @regimen = Regimen.find(params[:id])
  end

  def index
    @regimens = regimens.sort_by do |regimen|
      # All non-numeric regimens (eg Other) should be placed last
      regimen.name[0].match?(/\d/) ? regimen.name.to_i : REGIMEN_SORT_POSITION_LAST
    end
  end

  def new
    @regimen = Regimen.new
  end

  def create
    @regimen = RegimenService.create_regimen(post_params)

    if @regimen.errors.empty?
      redirect_to regimen_path(@regimen)
    else
      render :new
    end
  end

  def edit
    @regimen = Regimen.find(params[:id])
    @arvs = Drug.all_arvs
  end

  def update
    @regimen = Regimen.find(params[:id])

    if @regimen.update(params.require(:regimen).permit!)
      redirect_to edit_regimen_path(@regimen)
    else
      render :edit
    end
  end

  def destroy
    @regimen = Regimen.find(params[:id])
    @regimen.destroy

    redirect_to regimens_path
  end

  private

  def regimens
    Regimen.all
  end

  def post_params
    params.require(:regimen).permit(:name)
  end
end

app/helpers/regimens_helper.rb
module RegimensHelper
  def arvs
    Drug.all_arvs
        .sort_by(&:moh_name)
        .map { |arv| [arv.moh_name, arv.id] }
  end
end

app/views/regimens/_combination_fields.html.erb
<div class="regimen_combination form-row">
  <%= form.fields_for :drugs, RegimenCombinationDrug.new do |drugs_form| %>
    <%= render 'drug_fields', form: drugs_form %>
  <% end %>

  <%= link_to_add_fields '+', form, :drugs, class: 'btn btn-outline-default waves-effect' %>
  <a href="#" class="remove_fields btn btn-outline-danger waves-effect">-</a>
</div>

<style>
.btn {
  margin-top: 0;
  margin-bottom: 0;
  font-weight: bold;
}
</style>

app/views/regimens/_combinations.html.erb
<ul>
  <% regimen.combinations.each do |combination| %>
    <% next unless combination.id %>

    <li>
      <%= combination.name %>
      <%= link_to 'X', regimen_combination_path(combination), method: :delete,
                                                              class: 'btn btn-link text-danger',
                                                              data: { confirm: 'Are you sure about deleting this combination?' } %>
    </li>
  <% end %>
</ul>

app/views/regimens/_drug_fields.html.erb
<div class="col">
  <%= form.select :drug_id, arvs, { include_blank: '-- Select drug --'}, class: 'browser-default custom-select inline-select' %>
</div>

app/views/regimens/_new_form.html.erb
<% unless regimen.errors.empty? %>
  <div class="errors">
    <% regimen.errors.each do |item, error| %>
      <p class="error"><%= item %> - <%= error %></p>
    <% end %>
  </div>
<% end %>

<%= form_for regimen, url: { action: :create } do |form| %>
  <%= form.text_field :name, placeholder: 'Regimen name', class: 'form-control' %>

  <br />

  <h5>Combinations</h5>
  <%= form.fields_for :combinations, RegimenCombination.new do |combos_form| %>
    <%= render 'combination_fields', form: combos_form %>
  <% end %>


  <%= link_to_add_fields '+ Combination', form, :combinations, class: 'btn btn-outline-primary waves-effect', style: 'margin-top: 5px' %>

  <hr />

  <%= form.submit 'Create', class: "btn btn-primary" %>
<% end %>

app/views/regimens/_regimen.html.erb
<tr>
  <td class="<%= regimen.name[-1].casecmp?('P') ? 'paed-regimen-row' : 'adult-regimen-row' %>"><%= regimen.name %></td>
  <td>
    <ul>
      <% regimen.combinations.sort_by(&:name).each do |combination| %>
        <li><%= combination.name %></li>
      <% end %>
    </ul>
  </td>

  <td>
    <a href="<%= edit_regimen_path(regimen) %>" class="btn btn-link text-primary"><i class="fas fa-edit"></i></a>
  </td>
</tr>

app/views/regimens/edit.html.erb
<div class="container">
  <h1><%= @regimen.name %></h1>
  <hr />

  <%= render 'combinations', regimen: @regimen %>
  <%= render 'edit_form', regimen: @regimen %>
</div>

<%= javascript_pack_tag 'regimens/edit' %>

app/views/regimens/index.html.erb
 <div class="container">
  <div class="row">
    <div class="col-md-9">
      <h1>Regimens</h1>
    </div>
    <div class="col-md-3">
      <%= link_to 'Add Regimen', new_regimen_path, class: 'btn btn-primary', style: 'float: right' %>
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-12">
      <table id="regimens-table" class="table table-striped table-bordered">
        <thead class="regimen-row">
          <th>Regimen Name</th>
          <th>Drugs</th>
          <th>Action</th>
        </thead>
        <tbody>
          <%= render partial: 'regimen', collection: @regimens %>
        <tbody>
      </table>
    </div>
  </div>
</div>

<%= stylesheet_link_tag 'regimens' %>

app/views/regimens/new.html.erb
<div class="container">
  <%= render 'new_form', regimen: @regimen %>
</div>

<%= javascript_pack_tag 'regimens/edit' %>
<%= stylesheet_link_tag 'regimens' %>

app/views/regimens/show.html.erb
<div class="container">
  <h1><%= @regimen.name %></h1>
  <hr />

  <%= render 'combinations', regimen: @regimen %>
  
  <span>
    <%= link_to 'Edit', edit_regimen_path(@regimen), class: 'btn btn-primary' %>
    <%= link_to 'Delete', regimen_path(@regimen), class: 'btn btn-danger',
                                                      method: 'delete',
                                                      data: 'Are you sure you want to delete this regimen?' %>
  <span>
</div>

<%= javascript_pack_tag 'regimens/edit' %>